---

# SSH
ansible_user: ansible
ansible_public_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519_ansible.pub"

# Common role override
common_timezone: Europe/Moscow
common_locales:
  - en_US.UTF-8
  - ru_RU.UTF-8

common_packages:
  - vim
