---
- name: Allow loopback
  ansible.builtin.iptables:
    chain: INPUT
    in_interface: lo
    jump: ACCEPT
  notify: Save rules

- name: Drop invalid
  ansible.builtin.iptables:
    chain: "{{ item }}"
    ctstate: INVALID
    jump: DROP
  loop:
    - INPUT
    - FORWARD
  notify: Save rules

- name: Allow related, established connections
  ansible.builtin.iptables:
    chain: "{{ item }}"
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT
  loop:
    - INPUT
    - FORWARD
  notify: Save rules

- name: Allow input rules (new incoming packets)
  ansible.builtin.iptables:
    chain: INPUT
    protocol: "{{ item.protocol }}"
    in_interface: "{{ item.interface | default(omit) }}"
    destination_port: "{{ item.port | default(omit) }}"
    ctstate: NEW
    icmp_type: "{{ item.icmp_type | default(omit) }}"
    jump: ACCEPT
    comment: "{{ item.comment | default(omit) }}"
  loop: "{{ gateway_input_rules }}"
  notify: Save rules

- name: Allow forward rules
  ansible.builtin.iptables:
    chain: FORWARD
    in_interface: "{{ item.from }}"
    out_interface: "{{ item.to }}"
    ctstate: NEW
    jump: ACCEPT
    comment: "{{ item.comment | default(omit) }}"
  loop: "{{ gateway_forward_rules }}"

- name: Allow forward connection
  ansible.builtin.iptables:
    chain: FORWARD
    protocol: "{{ item.protocol }}"
    destination: "{{ item.destination }}"
    destination_port: "{{ item.destination_port }}"
    in_interface: "{{ item.in_interface }}"
    out_interface: "{{ item.out_interface }}"
    ctstate: NEW
    jump: ACCEPT
    comment: "{{ item.comment | default(omit) }}"
  loop: "{{ gateway_port_forwards }}"
