---
# tasks file for roles/gateway
- name: Validate all variables
  ansible.builtin.import_tasks: validate.yml

- name: Configure network gateway
  become: true
  block:
    - name: Install gateway components
      ansible.builtin.import_tasks: install.yml

    - name: Configure sysctl
      ansible.builtin.import_tasks: sysctl.yml

    - name: Import firewall configuration
      ansible.builtin.import_tasks: firewall.yml
