---
- name: Configure source nat
  ansible.builtin.iptables:
    table: nat
    chain: POSTROUTING
    out_interface: "{{ iface_wan }}"
    jump: MASQUERADE
  notify: Save rules
  when: gateway_enable_masquerade | bool

- name: Configure destination nat
  ansible.builtin.iptables:
    table: nat
    chain: PREROUTING
    in_interface: "{{ item.in_interface | default(omit) }}"
    protocol: "{{ item.protocol }}"
    destination_port: "{{ item.external_port }}"
    jump: DNAT
    to_destination: "{{ item.destination }}:{{ item.destination_port }}"
    comment: "{{ item.comment | default(omit) }}"
  notify: Save rules
  loop: "{{ gateway_port_forwards }}"
