---
- name: Set default filter policies
  ansible.builtin.iptables:
    table: filter
    chain: "{{ item.chain }}"
    policy: "{{ item.policy }}"
  loop:
    - { chain: INPUT, policy: "{{ gateway_default_input_policy }}" }
    - { chain: FORWARD, policy: "{{ gateway_default_forward_policy }}" }
    - { chain: OUTPUT, policy: "{{ gateway_default_output_policy }}" }
  notify: Save rules
