---
- name: Allow default policy filter
  ansible.builtin.iptables:
    table: filter
    chain: "{{ item }}"
    policy: ACCEPT
  loop:
    - INPUT
    - FORWARD
    - OUTPUT

- name: Allow default policy nat
  ansible.builtin.iptables:
    table: nat
    chain: "{{ item }}"
    policy: ACCEPT
  loop:
    - PREROUTING
    - INPUT
    - OUTPUT
    - POSTROUTING

- name: Flush filter
  ansible.builtin.iptables:
    table: filter
    flush: true

- name: Flush nat
  ansible.builtin.iptables:
    table: nat
    flush: true
