---
- name: Haproxy install and configuration
  become: true
  block:
    - name: Install haproxy
      ansible.builtin.import_tasks: install.yml

    - name: Configure haproxy
      ansible.builtin.import_tasks: configure.yml

    - name: Configure systemd
      ansible.builtin.import_tasks: systemd.yml
