---

# tasks file for kvm

- name: Install kvm hypervisor components
  become: true
  ansible.builtin.import_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- name: Grant KVM management permissions to administrator
  become: true
  ansible.builtin.user:
    name: "{{ kvm_admin }}"
    groups:
      - libvirt
      - kvm
    append: true
