---
gateway_iptables:
  - template_rules: "rules.v4.j2"
    tmp_rules: "/tmp/.rules.v4.tmp"
    backup_rules: "/tmp/.rules.v4.bak"
    restore_rules: "iptables-restore"
    save_rules: "iptables-save"
    rollback_pid: "/tmp/iptables_rollback.pid"

  - template_rules: "rules.v6.j2"
    tmp_rules: "/tmp/.rules.v6.tmp"
    backup_rules: "/tmp/.rules.v6.bak"
    restore_rules: "ip6tables-restore"
    save_rules: "ip6tables-save"
    rollback_pid: "/tmp/ip6tables_rollback.pid"

gateway_input_rules: []
gateway_forward_rules: []
gateway_port_forwards: []
gateway_default_input_policy: DROP
gateway_default_forward_policy: DROP
gateway_default_output_policy: ACCEPT
gateway_enable_masquerade: false

gateway_system_input_rules:
  - protocol: tcp
    port: "{{ ansible_port | default(22) }}"
    comment: "Ansible Management SSH Access"
