all:
  hosts:
    server1:
    server2:

# Example with groups:
#
# all:
#   children:
#     web:
#       hosts:
#         web01:
#           ansible_host: 192.168.1.201
#         web02:
#           ansible_hosts: 192.168.1.202
#
#     db:
#       hosts:
#         db01:
