---
# handlers file for roles/gateway
- name: Apply ipv4tables rules
  become: true
  ansible.builtin.command: iptables-restore /etc/iptables/rules.v4
  changed_when: true

- name: Apply ipv6tables rules
  become: true
  ansible.builtin.command: ip6tables-restore /etc/iptables/rules.v6
  changed_when: true
