---
# tasks file for common

- name: Apply base system configuration
  become: true
  block:
    - name: Configure system timezone
      ansible.builtin.import_tasks: timezone.yml

    - name: Configure system locale
      ansible.builtin.import_tasks: locale.yml

    - name: Manage Debian package dependencies
      ansible.builtin.import_tasks: debian_packages.yml
      when: ansible_os_family == 'Debian'
