---
# tasks file for common

- name: Apply common system configuration
  become: true
  block:
    - name: Configure timezone
      community.general.timezone:
        name: "{{ common_timezone }}"

    - name: Configure system locale
      community.general.locale_gen:
        name: "{{ item }}"
      loop: "{{ common_locales }}"

    - name: Install baseline apt packages
      ansible.builtin.package:
        name: "{{ common_packages }}"
        state: present
