---
# tasks file for docker

- name: Deploy docker
  become: true
  block:
    - name: Install docker on RedHat family
      ansible.builtin.import_tasks: redhat.yml
      when: ansible_os_family == 'RedHat'

    - name: Install docker on Debian family
      ansible.builtin.import_tasks: debian.yml
      when: ansible_os_family == 'Debian'

    - name: Add user in docker group
      ansible.builtin.user:
        name: "{{ docker_user }}"
        groups: docker
        append: true
      when: docker_user | length > 0

    - name: Configure docker network
      ansible.builtin.template:
        src: daemon.json.j2
        dest: /etc/docker/daemon.json
        mode: "0644"
      when: docker_configure_net | bool
      notify: Restart docker

    - name: Ensure docker daemon is running and enabled
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: true
