---
- name: Determine Docker repository OS
  ansible.builtin.set_fact:
    docker_repo_os: "{{ 'rhel' if ansible_distribution in ['Rocky', 'AlmaLinux', 'RedHat'] else ansible_distribution | lower }}"

- name: Add repo
  ansible.builtin.get_url:
    url: "https://download.docker.com/linux/{{ docker_repo_os }}/docker-ce.repo"
    dest: /etc/yum.repos.d/docker-ce.repo
    owner: root
    group: root
    mode: "0644"

- name: Install docker packages
  ansible.builtin.package:
    name: "{{ docker_packages }}"
    state: present
