---

- hosts: all
  gather_facts: false
  vars:
    ssh_key_path: "{{ lookup('env', 'HOME') + '/.ssh/id_ed25519.pub' }}"

  tasks:
    - name: Install SSH public key
      ansible.posix.authorized_key:
        user: "{{ ansible_user }}"
        state: present
        key: "{{ lookup('file', ssh_key_path) }}"
